# Scripts for running the tests inside docker
# NOTE: pypy not added here. Needs to be run in tox.
# NOTE: The tests are run with all dependencies installed

version: "3.4"

services:
  redis:
    image: redis:3.2
  py36:
    image: flask-resize-test:py36
    build:
      context: .
      dockerfile: ./test.Dockerfile
      args:
        PYTHON_VERSION: "3.6"
    command: test
    environment:
      REDIS_HOST: redis
    volumes:
        - ./tests:/app/tests
        - ./flask_resize:/app/flask_resize
  py37:
    image: flask-resize-test:py37
    build:
      context: .
      dockerfile: ./test.Dockerfile
      args:
        PYTHON_VERSION: "3.7"
    command: test
    environment:
      REDIS_HOST: redis
    volumes:
        - ./tests:/app/tests
        - ./flask_resize:/app/flask_resize
  py38:
    image: flask-resize-test:py38
    build:
      context: .
      dockerfile: ./test.Dockerfile
      args:
        PYTHON_VERSION: "3.8"
    command: test
    environment:
      REDIS_HOST: redis
    volumes:
        - ./tests:/app/tests
        - ./flask_resize:/app/flask_resize
  py39:
    image: flask-resize-test:py39
    build:
      context: .
      dockerfile: ./test.Dockerfile
      args:
        PYTHON_VERSION: "3.9"
    command: test
    environment:
      REDIS_HOST: redis
    volumes:
        - ./tests:/app/tests
        - ./flask_resize:/app/flask_resize
  lint:
    image: flask-resize-test:py39
    command: lint
    build:
      context: .
      dockerfile: ./test.Dockerfile
      args:
        PYTHON_VERSION: "3.9"
    volumes:
        - ./tests:/app/tests
        - ./flask_resize:/app/flask_resize
